### ISSUE TITLE
Implement TicketEvent Notifications

### ISSUE THREAD

**Issue by StephenRedd** [StephenRedd/TicketDesk#1]
Implement new Notifications system

New system will not be tied directly to email delivery. Instead, notifications are recorded for events that occur, and can support a variety of delivery mechanisms:

* Alert flag to indicate that the user should be alerted that the notification exists
* Read flag to indicate if the user has viewed an event notification
* Push flag to indicate that the notification may need to be delivered by a push mechanims (sms, email, etc.)

The actual management of push notifications will be handled by a different sub-system.

**Comment by vanquocktcn** [comment]
Hi StephenRedd ,

I can't find Database in your project.

Thanks

**Comment by StephenRedd** [comment]
For TD 2.5, it's created at runtime by entity framework migrations. For TD 2.1x, it's in the app_data folder in the web project.

--Stephen M. Redd
________________________________
