### ISSUE TITLE
Complete Search Queue

### ISSUE THREAD

**Issue by StephenRedd** [StephenRedd/TicketDesk#2]
Search should queue changes for indexing. Currently, this is wired directly to the indexer. 

- queue up changes or new tickets
  - queue  to the db for on-prem
  - azure storage queue for cloud
- background process dequeues and updates the index
  - timer loop for on-prem
  - webjob for azure

Design issues:
- Should the site itself trigger rebuilds periodically, on-startup, etc. or should this be handled by the timer/webjob also? 
- What level of admin control should be given regarding routine indexing behavior?
- Local debug and testing?

**Comment by StephenRedd** [comment]
Instead of queuing to the DB for on-prem deployments, we'll just use an in-memory static queue instead. Indexing in on-prem cases is incredibly fast, and there is little to gain by writing pending reindex requests to hard storage... that just adds load on the DB and grows the log without any significant pay-off. Instead, the on-prem version will queue in memory, and we'll just make sure that in-process queue items are dequeued and processed immediately as items arrive.

**Comment by kgilliam** [comment]
Nice to see you working on ticket desk again. :)

On Wed, Mar 4, 2015 at 3:43 AM, Stephen M. Redd <notifications@github.com>
wrote:

> Instead of queuing to the DB for on-prem deployments, we'll just use an
> in-memory static queue instead. Indexing in on-prem cases is incredibly
> fast, and there is little to gain by writing pending reindex requests to
> hard storage... that just adds load on the DB and grows the log without any
> significant pay-off. Instead, the on-prem version will queue in memory, and
> we'll just make sure that in-process queue items are dequeued and processed
> immediately as items arrive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StephenRedd/TicketDesk/issues/2#issuecomment-77117318>
> .
>



-- 
Kelly Gilliam
864.621.3925

**Comment by StephenRedd** [comment]
Yeah, I'm glad to have time for it again. The new job is very much an 8 to 5 deal... no one takes work home. In fact, they don't even setup to do full development locally since they rely on in-house shared DB servers. So, I have my evenings back to play with my own code... unless I find a part-time after-hours paid gig anyway.

I miss the team at EP though.

--Stephen M. Redd

**Comment by StephenRedd** [comment]
Search queues and azure webjob are not in place, and mostly working as intended. There will be later refactoring around first-run-setup and publishing/deployment.
