### ISSUE TITLE
Create connection string to a db on a different server

### ISSUE THREAD

**Issue by robbaron25** [StephenRedd/TicketDesk#35]
Stephen,

       I'm trying to get your TicketDesk application to run on my web server (Server 2008/IIS7) The application runs fine in my development environment, however I don't have a local version of SQL Server on the web server.  My applications connect to a dedicated SQL server (MSSQL 2008) on the same domain.  When I attempt to modify the connection strings to connect to the dedicated SQL server I am receiving an error.
 (1) The specified named connection is either not found in the configuration, not intended to be used with the EntityClient provider, or not valid.

Resulting in: An exception occurred while trying to create an instance of type 'TicketDesk.Domain.Repositories.ApplicationSettingsRepository'.

Could you please provide an example of what the connection string should look like connecting to a separate db/server?  Thank you. - Rob

**Comment by StephenRedd** [comment]
Sure, though this is a fairly common topic. TicketDesk 2.1x used entity framework, which has ugly connection strings.

    <name="TicketDeskEntities"
    connectionString="metadata=res://*/Models.TicketDeskEntities.csdl|res://*/Models.TicketDeskEntities.ssdl|res://*/Models.TicketDeskEntities.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=yourserver.domain.com;Integrated Security=true;initial catalog=TicketDesk;&quot;"
    providerName="System.Data.EntityClient">


The important bit is this segment:

    provider connection string=&quot;data source=yourserver.domain.com;Integrated Security=true;initial catalog=TicketDesk;

This is what a standard connection string would look like. The data source should be the name of your server. If you used a named SQL instance on the remote server, it would look like "yourserver.domain.com/InstanceName".

You can find several past posts on the codeplex discussion forum where others have had trouble with connection strings. This isn't, strictly speaking, a problem with TicketDesk. It's just that connection strings are complicate beasts, and old EF connection strings make it 10 times worse. TD 2.5 uses a normal connection string at least, so when that's ready to ship you can look forward to not having all the extra EF mess in there.
